#!/usr/bin/env python3

import colors as c

def ask(question):
    print(c.red + question + c.reset)
    answer = input("> " + c.base3).lower().strip()
    print(c.reset)
    return answer




print(c.cyan + '''


The user who wants to go
and cross the grid cavern of 
no return must awenser these
three quetions 

good luck >:->


'''
)


name = ask(c.cyan + "what is your name brave user? ")
quest = ask(c.red + "what is your quest user? ")


if name in ['lancelot', "galahad"]:
    question2 = input(c.blue + '''
    what is ur faveriot colur
    '''
    )
    if colour == 'blue':
        print("Right, ummmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm off you go")
    else:
        print("Thou art cast into the very very very deep cavern of the grid......    bye")

elif name == 'robin':
    capital = ask(c.red + "what is the captial of assyria")
    if capital in ['assur','ashur','nimrud','qalat sherqat','calah']:
        print(c.magenta + "All right a smart user of you go")
    else:
        print(c.red + "you doof its ASSUR, off you go into the cavern lets hope your dreezed before you hit the bottem.....")

elif name == 'arthur':
    bird = ask(c.yellow + "what is the airspeed of a unladen swallow? ")
    if bird in ['24','which one a aferican or euripean bird?']:
        print(c.cyan + '''

    bridge keeper: what i don't know that!!!

    (bridge keeper falls into cavern)

    arthur: well he's not smart
    '''
    )
       
    else:
        print(c.red + "user...   i  hope you have a slow plainful dereez")

