#!/usr/bin/env python3


import colors as c


c.clear_screen()
print(c.magenta + 'hello user,' + c.blue + ' which table would you like to see?' + c.green)

print('''



'''
)

number = input('enter number table --') 

print(c.magenta + 'please wait')

print('''...
...
...
...
'''
)

print(c.red + 'found it')
print(c.yellow + ' ')

for M in range(1,13,2):
    product = int(number) * M
    form = '{} x {} = {}'
    print(form.format(number,M,product))



