#!/usr/bin/env python3

import time

import colors as c

hundredths = 1


while True:
      time.sleep(1)
      print(c.clear)
      print(c.cyan + '[ctrl + c to stop]' + c.reset, end=': ')
      print(hundredths)
      hundredths +=1
