#!/usr/bin/env python3

import time
import colors as c

print(c.clear)
while True:

    for count in range(12):
        print(c.orange + 'badgers')
        time.sleep(0.5)
    
    for count in range(2):
        print(c.cyan + 'mushroom')
        time.sleep(0.8)
        
    for cpunt in range(1):
        print(c.clear)





