#!/usr/bin/env python-3

import time
import colors as c
import random as r



start =  input(c.base3 + 'welcome to the dice program, would you like to spin the dice?' + c.blue + '----->')

if start == 'yes':
    print(c.clear)

elif start == 'no':
    exit()


