#!/usr/bin/env python3

import time
import colors as c
import random 



start =  input(c.base3 + 'welcome to the dice program, would you like to spin the dice?' + c.blue + '----->   ')

if start == 'yes':
    print(c.clear)

elif start == 'no':
    exit()

sides = []


sides.append('''
 ---
! 1 !
 ---
''')

sides.append('''
 ---
! 2 !
 ---
''')

sides.append('''
 ---
! 3 !
 ---
''')

sides.append('''
 ---
! 4 !
 ---
''')

sides.append('''
 ---
! 5 !
 ---
''')

sides.append('''
 ---
! 6 !
 --- 
''')


print(random.choice(sides))
