#!/usr/bin/env python3

import time
import colors as c


print(c.clear)

waffle = input(c.yellow + 'Do you like waffles?' + c.orange + ' ----->  ' + c.yellow)

if waffle == 'yes':
    print(c.clear)

elif waffle == 'no':
    exit()
    print(c.red + 'not inviting you to breakfest')

pancakes = input(c.orange + 'Do you like pancakes?' + c.yellow + ' ---->  ' + c.orange)

if pancakes == 'yes':
    print(c.clear)

elif  pancakes == 'no':
    exit()
  

toast = input(c.yellow + 'Do you like french toast?' + c.orange + ' ----->  ')

if toast == 'yes':
    print(c.clear)
    print(c.green + 'yes im inviting u for breakfest!!!')
    time.sleep(3)
    while True:
        print(c.magenta + 'yeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')

elif toast == 'no':
    exit()  
    print(c.red + '>:-/ waffle hater')
